<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-SETN8PHA" failures="1" tests="6" name="packageAPI.principal" time="2.538" errors="0" timestamp="2021-03-11T00:02:24 CET" skipped="0">
  <testcase classname="packageAPI.principal" name="crear_usuario" time="1.751">
    <failure message="Server returned HTTP response code: 409 for URL: https://api-testing-conference.herokuapp.com/v1.0/users" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Server returned HTTP response code: 409 for URL: https://api-testing-conference.herokuapp.com/v1.0/users
at org.testng.Assert.fail(Assert.java:97)
at packageAPI.principal.crear_usuario(principal.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- crear_usuario -->
  <system-out/>
  <testcase classname="packageAPI.principal" name="obtener_usuarios" time="0.287"/>
  <system-out/>
  <testcase classname="packageAPI.principal" name="crear_mensaje_foro" time="0.104"/>
  <system-out/>
  <testcase classname="packageAPI.principal" name="obtener_mensajes_foro" time="0.128"/>
  <system-out/>
  <testcase classname="packageAPI.principal" name="enviar_mensaje_privado" time="0.171"/>
  <system-out/>
  <testcase classname="packageAPI.principal" name="obtener_mensaje_privado" time="0.097"/>
  <system-out/>
</testsuite> <!-- packageAPI.principal -->
